### ISSUE TITLE
Pls add posibility to close GPIO Viewer webpage on request

### ISSUE THREAD

**Issue by arendst** [thelastoutpostworkshop/GPIOViewerVueApplication#2]
I open the GPIO Viewer in another window/tab. If the device is restarted it would be nice to close the GPIO Viewer window too.

Pls add below code as additional eventListenener:

```
  source.addEventListener(
    "close",
    (e: MessageEvent) => {
      console.log("Closing");
  	  self.close();
    },
    false
  );
```

Thx in advance

**Comment by thelastoutpostworkshop** [comment]
the change is now in production

**Comment by arendst** [comment]
Thx. Verified and works as expected.
